Winner:
  type: entity
  table: winners
  indexes:
    email_index:
      columns: [ email ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
      length: 32
      unique: true
    name:
      type: string
      length: 50
    ip_addr:
      type: string
      length: 15 # xxx.xxx.xxx.xxx, not handling IPv6
      unique: true
  oneToOne:
    prize:
      targetEntity: Prize
      joinColumn:
        name: prize_id
        referencedColumnName: id
        onDelete: CASCADE